---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-labels-dana-io-v1alpha1-namespacelabel
  failurePolicy: Fail
  name: vnamespacelabel-v1alpha1.kb.io
  rules:
  - apiGroups:
    - labels.dana.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespacelabels
  sideEffects: None
